### ISSUE TITLE
RivalHarvester Hoe Support

### ISSUE THREAD

**Issue by Zsomi** [Wertik/BlockRegen#37]
My current problem is that I'm using the RivalHarvesterHoe plugin and if I use its hoe to knock out the blockgen wheat, it doesn't grow back + I don't get the reward.

https://docs.rivaldev.xyz/rival-tools/rival-harvester-hoes/api

**Comment by Wertik** [comment]
Unfortunately I don't have a copy of this plugin so I wouldn't be able to test any possible support. However, there were some changes to this plugin since then, might already work just fine.

As this is quite an old issue (sorry for response time) I don't think you'd need this feature anymore. If so, reopen and we can discuss further.
